const assert = require('node:assert/strict');
const {esc,label,duration,graphData,definitionInvocation,fileChanges,nodeCard,executionRole,activityRows}=require('./monitor.js');
assert.equal(esc(`<img src='x' onerror="evil()">&`),'&lt;img src=&#39;x&#39; onerror=&quot;evil()&quot;&gt;&amp;');
assert.equal(label('ready'),'Подготовлен к выдаче Attempt');
assert.equal(label('pending'),'Attempt передан агенту');
assert.equal(label('running'),'Исполнение начато');
assert.equal(label('skipped'),'Будет пропущен');
assert.equal(label('future'),'Может быть выполнен');
assert.equal(label('no_work'),'Нет работы');
assert.equal(definitionInvocation({definitions:[{ref:{digest:'workflow'},bytes:'{"id":"plan"}'}],invocations:{one:{id:'actual',workflow_ref:{digest:'workflow'}}}},'plan'),'actual');
assert.equal(definitionInvocation({definitions:[{ref:{digest:'workflow'},bytes:'{"id":"plan"}'}],invocations:{one:{id:'first',workflow_ref:{digest:'workflow'}},two:{id:'second',workflow_ref:{digest:'workflow'}}}},'plan'),'__definition__');
assert.equal(duration({quality:'unknown'}),'Неизвестно');
assert.match(duration({quality:'partial',known_ms:2500}),/не менее 2.5 с/);
assert.match(duration({quality:'measured',value_ms:0}),/^0 мс/);
assert.match(duration({quality:'partial',known_ms:0,estimate_ms:300000}),/^около 5.0 мин/);
const workflow={definition:{entry:'choose',stages:{choose:{kind:'choice',branches:[{id:'yes',next:'fan'},{id:'no',next:'end'}]},fan:{kind:'parallel',branches:[{id:'left',workflow_ref:{id:'child'}},{id:'right',workflow_ref:{id:'child'}}],on:{ok:'repeat'}},repeat:{kind:'repeat',body_workflow_ref:{id:'child'},on_complete:{ok:'end'},on_limit:'end'},end:{kind:'finish'}}}};
const run={invocations:{root:{ready_stages:['fan']},child:{id:'child',branch_id:'left',caller_stage_activation_id:'activation',status:'running'}},activations:{choose:{id:'c',stage_id:'choose',workflow_invocation_id:'root',status:'completed'},fan:{id:'activation',stage_id:'fan',workflow_invocation_id:'root',status:'running'},other:{stage_id:'end',workflow_invocation_id:'other',status:'completed'}}};
const graph=graphData(workflow,run,'root');
assert.equal(graph.nodes.find(n=>n.id==='end').state,'future');
assert.equal(graph.nodes.find(n=>n.id==='fan / left').invocation,'child');
assert.equal(graph.nodes.find(n=>n.id==='fan / right').state,'future');
assert.equal(graph.nodes.filter(n=>n.kind==='repeat').length,1);
assert.ok(graph.edges.some(e=>e.from==='choose' && e.to==='fan'));
assert.ok(graph.edges.some(e=>e.from==='choose' && e.to==='fan' && e.path));
assert.ok(graph.edges.some(e=>e.from==='fan / right' && e.to==='repeat'));
const choiceGraph=graphData({definition:{entry:'choose',stages:{choose:{kind:'choice',branches:[{id:'yes',next:'yes'},{id:'no',next:'no'}]},yes:{kind:'step'},no:{kind:'step'}}}}, {}, '',[{stage_id:'choose',next_stage_id:'yes',route:'branch',branch_id:'yes'}]);
assert.equal(choiceGraph.nodes.find(n=>n.id==='no').state,'skipped');
assert.equal(choiceGraph.nodes.find(n=>n.id==='no').visual,'skipped');
assert.match(choiceGraph.nodes.find(n=>n.id==='no').reason,/Выбран маршрут yes → yes/);
assert.equal(choiceGraph.nodes.find(n=>n.id==='yes').state,'future');
const choiceEdges=choiceGraph.edges.filter(e=>e.from==='choose');
assert.equal(new Set(choiceEdges.map(e=>e.fromPort)).size,choiceEdges.length);
assert.ok(choiceEdges.find(e=>e.to==='no').muted);
const excludedGraph=graphData({definition:{entry:'choose-security',stages:{'choose-security':{kind:'choice',branches:[{id:'enabled',next:'security',predicate:{op:'eq',left:{ref:{from:'workflow_input',port:'security_enabled'}},right:{kind:'literal',value:true}}}],default:'review'},security:{kind:'step'},review:{kind:'step'}}}}, {}, '', [], {security_enabled:'false'});
assert.equal(excludedGraph.nodes.find(n=>n.id==='security').state,'skipped');
assert.equal(excludedGraph.nodes.find(n=>n.id==='review').state,'future');
const skippedCard=nodeCard(choiceGraph,'no',{context:{inputs:{brief:{}}},accepted:{outputs:{result:{}}}});
assert.match(skippedCard,/Закреплённый узел/);
assert.match(skippedCard,/Входящие переходы/);
assert.match(skippedCard,/Исходящие переходы/);
assert.match(skippedCard,/Выбран маршрут yes/);
assert.match(skippedCard,/Входы: brief/);
const arrivalGraph=graphData({definition:{entry:'plan',stages:{plan:{kind:'step',on:{no_work:'abandoned'}},abandoned:{kind:'finish'}}}},{activations:{plan:{stage_id:'plan',workflow_invocation_id:'root',status:'completed',step_instance_id:'step-plan'}}},'root');
const arrivedCard=nodeCard(arrivalGraph,'abandoned',{}, {attempts:{a:{step_instance_id:'step-plan',accepted:{summary:'План не требует работы'}}}});
assert.match(arrivedCard,/Почему выбран этот переход/);
assert.match(arrivedCard,/Нет работы.*План не требует работы/);
const readyGraph=graphData({definition:{entry:'ready',stages:{ready:{kind:'step'}}}},{ready_stages:['ready']},'');
assert.equal(readyGraph.nodes[0].visual,'reachable');
const unknownGraph=graphData({definition:{entry:'missing',stages:{missing:{kind:'step'}}}},{settled:true},'');
assert.equal(unknownGraph.nodes[0].visual,'unknown');
assert.match(unknownGraph.nodes[0].reason,/не записана/);
assert.deepEqual([...new Set(choiceEdges.map(e=>e.route))],['forward','skipped']);
const cycle=graphData({definition:{entry:'a',stages:{a:{on:{go:'b'}},b:{on:{again:'a'}}}}},{},'');
assert.equal(cycle.nodes.length,2);assert.ok(Number.isFinite(cycle.width));
assert.equal(fileChanges(null,{files:[]}),null);
assert.deepEqual(fileChanges({files:[{path:'a',ref:{digest:'old'}},{path:'deleted',ref:{digest:'d'}}]},{files:[{path:'a',ref:{digest:'new'}},{path:'new',ref:{digest:'n'}}]}),[{path:'a',change:'Изменён'},{path:'deleted',change:'Удалён'},{path:'new',change:'Добавлен'}]);
assert.deepEqual(executionRole({session:{principal_id:'host:codex'},started:null}),{kind:'Внешний host',detail:'host:codex',state:'Выдано · ожидается отчёт host'});
assert.equal(executionRole({process:{executable:'go'},started:{}},null).kind,'Локальная программа');
assert.equal(executionRole(null,{kind:'call'}).detail,'Не является fork Run');
assert.match(executionRole(null,null).kind,/не записана/);
const activity=activityRows({attempts:{one:{id:'attempt:one',session:{principal_id:'host:one'}}},activations:{ready:{id:'activation:ready',stage_id:'plan',status:'ready'}},pending_decision:{attempt_id:'attempt:one',decision_id:'decision:go'},wait_registrations:{wait:{activation_id:'activation:wait',target_stage_id:'signal',status:'active'}},fork:{source_run_id:'run:source'}});
assert.equal(activity.length,5);assert.match(activity[0].detail,/ожидается отчёт/);
assert.equal(activityRows({fork:{source_run_id:'run:source',reason:'project continuation'}})[0].title,'Продолжение от Run');
const recovered={root_workflow_invocation_id:'root',recovery:{source_run_id:'run:source',frontier_stage_id:'tests',reused:[{stage_id:'verify'}],root_output_refs:{verify:{implementation:{artifact_id:'artifact:old'}}}}};
assert.equal(graphData({definition:{entry:'verify',stages:{verify:{kind:'call',on:{succeeded:'tests'}},tests:{kind:'step'}}}},recovered,'root').nodes[0].state,'reused');
assert.match(activityRows(recovered)[0].detail,/1 узлов взято/);
console.log('monitor UI: status wording, escaping, timing quality, graph paths/ports/parallel/repeat/cycles, file evidence passed');

// Exercise the actual pre-paint script, including browsers that deny storage.
const vm = require('node:vm');
const fs = require('node:fs');
const themeSource = fs.readFileSync(require('node:path').join(__dirname,'monitor-theme.js'),'utf8');
function themeSession(saved, dark, blocked=false) {
 const callbacks={},media={matches:dark,addEventListener:(_,fn)=>callbacks.system=fn};
 const select={value:'',addEventListener:(_,fn)=>callbacks.select=fn};
 const document={documentElement:{dataset:{}},addEventListener:(_,fn)=>callbacks.ready=fn,getElementById:()=>select};
 const localStorage={getItem:()=>{if(blocked)throw Error('denied');return saved;},setItem:(_,value)=>{if(blocked)throw Error('denied');saved=value;}};
 vm.runInNewContext(themeSource,{window:{matchMedia:()=>media},document,localStorage});
 const firstPaint=document.documentElement.dataset.theme;
 callbacks.ready();
 return {document,firstPaint,select,change(value){select.value=value;callbacks.select();},system(value){media.matches=value;callbacks.system();},saved:()=>saved};
}
const automatic=themeSession(null,true);
assert.equal(automatic.firstPaint,'dark');assert.equal(automatic.select.value,'system');
automatic.system(false);assert.equal(automatic.document.documentElement.dataset.theme,'light');
automatic.change('dark');automatic.system(false);
assert.equal(automatic.document.documentElement.dataset.theme,'dark');
assert.equal(themeSession(automatic.saved(),false).firstPaint,'dark');
automatic.change('system');assert.equal(automatic.document.documentElement.dataset.theme,'light');
assert.equal(themeSession('invalid',true).firstPaint,'dark');
const denied=themeSession(null,false,true);denied.change('dark');
assert.equal(denied.document.documentElement.dataset.theme,'dark');
console.log('monitor themes: pre-paint, persistence, system changes and denied storage passed');
