const assert = require('node:assert/strict');
const {esc,duration,graphData,fileChanges}=require('./monitor.js');
assert.equal(esc(`<img src='x' onerror="evil()">&`),'&lt;img src=&#39;x&#39; onerror=&quot;evil()&quot;&gt;&amp;');
assert.equal(duration({quality:'unknown'}),'Неизвестно');
assert.match(duration({quality:'partial',known_ms:2500}),/не менее 2.5 с/);
assert.match(duration({quality:'measured',value_ms:0}),/^0 мс/);
assert.match(duration({quality:'partial',known_ms:0,estimate_ms:300000}),/^около 5.0 мин/);
const workflow={definition:{entry:'choose',stages:{choose:{kind:'choice',branches:[{id:'yes',next:'fan'},{id:'no',next:'end'}]},fan:{kind:'parallel',branches:[{id:'left',workflow_ref:{id:'child'}},{id:'right',workflow_ref:{id:'child'}}],on:{ok:'repeat'}},repeat:{kind:'repeat',body_workflow_ref:{id:'child'},on_complete:{ok:'end'},on_limit:'end'},end:{kind:'finish'}}}};
const run={invocations:{root:{ready_stages:['fan']},child:{id:'child',branch_id:'left',caller_stage_activation_id:'activation',status:'running'}},activations:{choose:{id:'c',stage_id:'choose',workflow_invocation_id:'root',status:'completed'},fan:{id:'activation',stage_id:'fan',workflow_invocation_id:'root',status:'running'},other:{stage_id:'end',workflow_invocation_id:'other',status:'completed'}}};
const graph=graphData(workflow,run,'root');
assert.equal(graph.nodes.find(n=>n.id==='end').state,'future');
assert.equal(graph.nodes.find(n=>n.id==='fan / left').invocation,'child');
assert.equal(graph.nodes.find(n=>n.id==='fan / right').state,'future');
assert.equal(graph.nodes.filter(n=>n.kind==='repeat').length,1);
assert.ok(graph.edges.some(e=>e.from==='choose' && e.to==='fan'));
assert.ok(graph.edges.some(e=>e.from==='fan / right' && e.to==='repeat'));
const choiceGraph=graphData({definition:{entry:'choose',stages:{choose:{kind:'choice',branches:[{id:'yes',next:'yes'},{id:'no',next:'no'}]},yes:{kind:'step'},no:{kind:'step'}}}}, {}, '',[{stage_id:'choose',next_stage_id:'yes',route:'branch',branch_id:'yes'}]);
assert.equal(choiceGraph.nodes.find(n=>n.id==='no').state,'unchosen');
assert.equal(choiceGraph.nodes.find(n=>n.id==='yes').state,'future');
const cycle=graphData({definition:{entry:'a',stages:{a:{on:{go:'b'}},b:{on:{again:'a'}}}}},{},'');
assert.equal(cycle.nodes.length,2);assert.ok(Number.isFinite(cycle.width));
assert.equal(fileChanges(null,{files:[]}),null);
assert.deepEqual(fileChanges({files:[{path:'a',ref:{digest:'old'}},{path:'deleted',ref:{digest:'d'}}]},{files:[{path:'a',ref:{digest:'new'}},{path:'new',ref:{digest:'n'}}]}),[{path:'a',change:'Изменён'},{path:'deleted',change:'Удалён'},{path:'new',change:'Добавлен'}]);
console.log('monitor UI: escaping, timing quality, graph scope/parallel/repeat/cycles, file evidence passed');

// Exercise the actual pre-paint script, including browsers that deny storage.
const vm = require('node:vm');
const fs = require('node:fs');
const themeSource = fs.readFileSync(require('node:path').join(__dirname,'monitor-theme.js'),'utf8');
function themeSession(saved, dark, blocked=false) {
 const callbacks={},media={matches:dark,addEventListener:(_,fn)=>callbacks.system=fn};
 const select={value:'',addEventListener:(_,fn)=>callbacks.select=fn};
 const document={documentElement:{dataset:{}},addEventListener:(_,fn)=>callbacks.ready=fn,getElementById:()=>select};
 const localStorage={getItem:()=>{if(blocked)throw Error('denied');return saved;},setItem:(_,value)=>{if(blocked)throw Error('denied');saved=value;}};
 vm.runInNewContext(themeSource,{window:{matchMedia:()=>media},document,localStorage});
 const firstPaint=document.documentElement.dataset.theme;
 callbacks.ready();
 return {document,firstPaint,select,change(value){select.value=value;callbacks.select();},system(value){media.matches=value;callbacks.system();},saved:()=>saved};
}
const automatic=themeSession(null,true);
assert.equal(automatic.firstPaint,'dark');assert.equal(automatic.select.value,'system');
automatic.system(false);assert.equal(automatic.document.documentElement.dataset.theme,'light');
automatic.change('dark');automatic.system(false);
assert.equal(automatic.document.documentElement.dataset.theme,'dark');
assert.equal(themeSession(automatic.saved(),false).firstPaint,'dark');
automatic.change('system');assert.equal(automatic.document.documentElement.dataset.theme,'light');
assert.equal(themeSession('invalid',true).firstPaint,'dark');
const denied=themeSession(null,false,true);denied.change('dark');
assert.equal(denied.document.documentElement.dataset.theme,'dark');
console.log('monitor themes: pre-paint, persistence, system changes and denied storage passed');
